### ISSUE TITLE
Update library versions

### ISSUE THREAD

**Issue by josdem** [josdem/webdriverio-android#6]
As a **user**, I would like to update library versions **so that** I can have the latest versions integrated.

**Acceptance Criteria**

I have the latest library versions of the following:
- NodeJS
- Appium
- Applitools

**Comment by josdem** [comment]
We found an error updating libraries updating 8.0.0 or above.
`2023-11-29T16:13:30.359Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-11-29T16:13:30.360Z ERROR @wdio/appium-service: Appium is not installed locally. Please install via e.g. `npm i --save-dev appium`.
If you use globally installed appium please add: `appium: { command: 'appium' }`
to your wdio.conf.js!`

**Comment by josdem** [comment]
I made it works with WDIO version `7.33.0`, however throws an error with Applitools integration:
`[0-0] Error in "Should validate launcher.validate message changing screen"
Error: Unable to extract broker url from the device
    at getNMLClient (/home/josdem/Projects/webdriverio-android/node_modules/@applitools/core/dist/automation/get-nml-client.js:38:19)
    at async Object.check (/home/josdem/Projects/webdriverio-android/node_modules/@applitools/core/dist/ufg/check.js:97:35)
    at async Eyes.check (/home/josdem/Projects/webdriverio-android/node_modules/@applitools/eyes/dist/Eyes.js:268:9)
    at async Object.checkWindow (/home/josdem/Projects/webdriverio-android/test/utils/applitools.util.js:26:3)
    at async Context.<anonymous> (/home/josdem/Projects/webdriverio-android/test/specs/launcher.applitools.spec.js:16:5)`
